export const list = [
  {
    detail: "Senior UX Designer",
    created: "17 Oct, 2020",
    createdBy: "Cody Fisher",
    expired: "24 May, 2020",
    assignedBy: "Leslie Alexander",
    candidates: 426,
    response: 200,
    analysed: 160,
    shortlisted: 40,
    status: true,
  },
  {
    detail: "User Interface Intern",
    created: "17 Oct, 2020",
    createdBy: "Savannah Nguyen",
    expired: "24 May, 2020",
    assignedBy: "Darrell Steward",
    candidates: 346,
    response: 200,
    analysed: 160,
    shortlisted: 40,
    status: false,
  },
  {
    detail: "UI Designer - 1 yrs Exp. ",
    created: "17 Oct, 2020",
    createdBy: "Jenny Wilson",
    expired: "24 May, 2020",
    assignedBy: "Devon Lane",
    candidates: 426,
    response: 200,
    analysed: 160,
    shortlisted: 40,
    status: true,
  },
  {
    detail: "User Interface Intern",
    created: "17 Oct, 2020",
    createdBy: "Savannah Nguyen",
    expired: "24 May, 2020",
    assignedBy: "Darrell Steward",
    candidates: 346,
    response: 200,
    analysed: 160,
    shortlisted: 40,
    status: false,
  },
  {
    detail: "User Interface Intern",
    created: "17 Oct, 2020",
    createdBy: "Savannah Nguyen",
    expired: "24 May, 2020",
    assignedBy: "Darrell Steward",
    candidates: 346,
    response: 200,
    analysed: 160,
    shortlisted: 40,
    status: false,
  },
  {
    detail: "User Interface Intern",
    created: "17 Oct, 2020",
    createdBy: "Savannah Nguyen",
    expired: "24 May, 2020",
    assignedBy: "Darrell Steward",
    candidates: 346,
    response: 200,
    analysed: 160,
    shortlisted: 40,
    status: false,
  },
];
